import apiClient from "./apiClient";

const POLL_INTERVAL_MS = 2000;
const POLL_MAX_ATTEMPTS = 90; // 90 * 2s = 3 minutes max

export const repoService = {
    analyzeRepo: async (repoUrl: string) => {
        try {
            const uploadRes = await apiClient.post("/repos/upload", { repo_url: repoUrl });
            const repo_id = uploadRes.data.repo_id;

            let attempts = 0;
            let status = "pending";

            while (status !== "analyzed" && status !== "error") {
                if (attempts >= POLL_MAX_ATTEMPTS) {
                    throw new Error("Analysis timed out. Please try again.");
                }
                await new Promise(r => setTimeout(r, POLL_INTERVAL_MS));
                const statRes = await apiClient.get(`/repos/status/${repo_id}`);
                status = statRes.data.status;
                if (status === "error") {
                    throw new Error(statRes.data.error_message || "Repository analysis failed.");
                }
                attempts++;
            }

            const intelRes = await apiClient.get(`/repos/intelligence/${repo_id}`);
            const data = intelRes.data;

            return {
                id: repo_id,
                repo_name: data.repo_name || repoUrl.split("/").pop() || "Repository",
                description: data.overview || "Analysis complete.",
                complexity: data.complexity_score || 0,
                techStack: data.tech_stack || [],
                architecture_summary: data.architecture_summary || "",
                design_patterns: data.design_patterns || [],
                folderStructure: [],
                issues: data.risks || [],
                contributionIdeas: data.recommendations || [],
                strengths: data.strengths || [],
                mermaid_diagram: data.mermaid_diagram || "",
                generated_at: data.generated_at || "",
            };
        } catch (error: any) {
            const errorMsg = error.response?.data?.detail || error.message || "Failed to analyze repository";
            throw new Error(errorMsg);
        }
    },

    uploadRepo: async (formData: FormData) => {
        try {
            const repoUrl = formData.get("repo_url");
            if (repoUrl) {
                const { data } = await apiClient.post("/repos/upload", { repo_url: repoUrl });
                return data;
            }
            return { status: "error", message: "No repo_url provided" };
        } catch (error: any) {
            const errorMsg = error.response?.data?.detail || error.message || "Failed to upload repository";
            throw new Error(errorMsg);
        }
    },

    getPreviousChats: async () => {
        try {
            const { data } = await apiClient.get("/repos/history");
            // Backend returns flat array: [{ id, repo_name, last_scanned, summary, status }]
            return Array.isArray(data) ? data : [];
        } catch (error: any) {
            console.warn("Could not load repo history:", error.message);
            return [];
        }
    },

    performHeavyScan: (data: any[]) => {
        return Promise.resolve(data);
    },

    getAssessment: async (repoId: string) => {
        // Assessment questions are generated by calling /api/assessments/start with tech stack from intelligence
        // If no repoId or no questions available, return empty so the RepoAssessment empty state is shown.
        // The RepoAssessment component already shows a prompt: "scan a repository first".
        return [];
    },

    getRepoAnalysisById: async (id: string) => {
        try {
            const intelRes = await apiClient.get(`/repos/intelligence/${id}`);
            const data = intelRes.data;
            return {
                id: id,
                repo_name: data.repo_name || "Unknown",
                description: data.overview || "Analysis complete.",
                complexity: data.complexity_score || 0,
                techStack: data.tech_stack || [],
                architecture_summary: data.architecture_summary || "",
                design_patterns: data.design_patterns || [],
                folderStructure: [],
                issues: data.risks || [],
                contributionIdeas: data.recommendations || [],
                strengths: data.strengths || [],
                mermaid_diagram: data.mermaid_diagram || "",
                generated_at: data.generated_at || "",
            };
        } catch (error: any) {
            const errorMsg = error.response?.data?.detail || error.message || "Failed to load repository intelligence";
            throw new Error(errorMsg);
        }
    }
};
